### ISSUE TITLE
您好，我采集的Mid360数据算法开始时里程计就飘了，好几个数据都是如此

### ISSUE THREAD

**Issue by af-doom** [YWL0720/I2EKF-LO#1]

**Comment by YWL0720** [comment]
方便的话，可以提供数据集链接么？我来测试下

**Comment by af-doom** [comment]
> 方便的话，可以提供数据集链接么？我来测试下

您好，我正在上传，感谢

**Comment by af-doom** [comment]
> 方便的话，可以提供数据集链接么？我来测试下
您好，以下是两个数据
 [https://1drv.ms/u/c/be458a745a2235e4/EbEP13-n_apOg6g8eCvs7McBrL0A8c_ivkdTOhuarkDatg?e=Qqt5AL](url)
[https://1drv.ms/u/c/be458a745a2235e4/EfaQK--VySdLjUzORxyi75QBl38c9z27gyhcdaMcyANnkw?e=YjNubs](url)

**Comment by af-doom** [comment]
> > 方便的话，可以提供数据集链接么？我来测试下
> > 您好，以下是两个数据
 1.https://1drv.ms/u/c/be458a745a2235e4/EfaQK--VySdLjUzORxyi75QBl38c9z27gyhcdaMcyANnkw?e=bnXxpY
2.https://1drv.ms/u/c/be458a745a2235e4/EbEP13-n_apOg6g8eCvs7McBrL0A8c_ivkdTOhuarkDatg?e=lS4SY6

**Comment by af-doom** [comment]
> 方便的话，可以提供数据集链接么？我来测试下

您好，数据已上传

**Comment by af-doom** [comment]
> _No description provided._

测试了Mid-70没有问题

**Comment by YWL0720** [comment]
好的收到，我会尽快测试下 给你回复

**Comment by af-doom** [comment]
> 好的收到，我会尽快测试下 给你回复

太感谢了，我迫切需要一个里程计

**Comment by af-doom** [comment]
> 好的收到，我会尽快测试下 给你回复

另外，我在Lidar_IMU_INIT上测试单独激光里程计我的Mid-360数据也会飘

**Comment by af-doom** [comment]
> 好的收到，我会尽快测试下 给你回复

您好，我还是没排查出原因，不知道是不是我电脑环境的问题

**Comment by YWL0720** [comment]
您好，初步分析不是环境的问题，我注意到提供的bag里，/livox/lidar的频率为50Hz，每一帧点云的数量和视野范围变化较大，所处的环境相邻帧之间在z轴方向的约束有限，容易产生漂移。如果没有特殊需求的话，建议修改livox驱动，改为10Hz的点云输出。或尝试初始阶段静止一段时间，积累足够的地图点后再移动。

**Comment by af-doom** [comment]
> 您好，初步分析不是环境的问题，我注意到提供的bag里，/livox/lidar的频率为50Hz，每一帧点云的数量较少，视野范围变化较大，所处的环境相邻帧之间在z轴方向的约束有限，容易产生漂移。如果没有特殊需求的话，建议修改livox驱动，改为10Hz的点云输出。或尝试初始阶段静止一段时间，积累足够的地图点后再移动。

非常感谢您的答复。还有两个问题请教您，Mid-70测试里程计的时候有点抖，另外echo mid-360数据的时候最大line是3，这是正常的吗，为啥配置文件都是6

**Comment by YWL0720** [comment]
抖的话可以尝试调节acc_cov和gyr_cov。正常情况下mid360的line值在0-3之间，tag的含义可以参考https://www.livoxtech.com/cn/showcase/livox-tag
